In [1]:
import numpy as np
#陣列運算
a = np.array([1, 3, 5, 7, 9])
a *= 10
a

array([10, 30, 50, 70, 90])

In [2]:
a = np.array([1, 3, 5, 7, 9])
b = np.array([2, 4 , 6, 8, 10])

#陣列運算
a + b

array([ 3,  7, 11, 15, 19])

In [3]:
#2維ndarray
arr = np.array([[1, 3, 5],[2, 4, 6]])
arr.ndim #維度
arr.shape #形狀
arr.size #元素數量
arr.dtype #型別

dtype('int64')

In [4]:
np.random.rand()
np.random.rand(30,4)

array([[0.57543488, 0.9341004 , 0.05424923, 0.63881887],
       [0.69791917, 0.69805739, 0.56852415, 0.67132269],
       [0.52089734, 0.33980266, 0.92767177, 0.90451959],
       [0.75402573, 0.17503158, 0.92284022, 0.79612519],
       [0.78806102, 0.78669629, 0.45690613, 0.77292707],
       [0.40538756, 0.48302925, 0.57845089, 0.8098417 ],
       [0.97982595, 0.80180553, 0.71569684, 0.20300174],
       [0.32171284, 0.92541113, 0.60537873, 0.35609967],
       [0.49185828, 0.03412865, 0.7068043 , 0.72084163],
       [0.38419731, 0.28748683, 0.61066959, 0.27999922],
       [0.4703042 , 0.14759051, 0.2377327 , 0.77182485],
       [0.46176584, 0.60866198, 0.66346981, 0.457128  ],
       [0.24943779, 0.39418021, 0.00675705, 0.75057708],
       [0.42599615, 0.62658492, 0.98047311, 0.70345177],
       [0.31175396, 0.09508898, 0.83082175, 0.07356665],
       [0.8199429 , 0.1612726 , 0.39922262, 0.2339895 ],
       [0.80277398, 0.42377969, 0.58838041, 0.63137642],
       [0.99231103, 0.41291824,

In [5]:
scores = np.random.randint(50,101,size=(5,5))
scores

array([[81, 80, 75, 50, 95],
       [54, 81, 67, 73, 76],
       [96, 86, 78, 96, 51],
       [83, 56, 52, 87, 86],
       [71, 57, 93, 70, 68]], dtype=int32)