In [1]:
import numpy as np
arr = np.arange(10) * 10
arr

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#索引
arr[1]

#slice
arr[:5] #前5個
arr[-5:] #最後5個


array([50, 60, 70, 80, 90])

In [6]:
scores = np.random.randint(50,101, size=(50, 5))
scores

array([[ 58,  79,  78,  92,  81],
       [ 76, 100,  87,  83,  63],
       [ 53,  71,  73,  84,  74],
       [ 68,  72,  63,  93,  67],
       [ 84,  77,  93,  90,  94],
       [ 78,  73,  78,  67,  85],
       [ 91,  56,  72,  75,  97],
       [ 69,  56,  69,  71,  70],
       [ 78,  57,  76,  90,  51],
       [ 84,  69,  78,  89,  72],
       [ 57,  68,  98,  78,  55],
       [ 80,  80,  61,  82,  62],
       [ 83,  76,  80,  64,  74],
       [ 80,  82,  62,  77,  54],
       [ 92,  68,  51,  84,  95],
       [ 77,  93,  78,  99,  65],
       [ 74,  53,  98,  73,  80],
       [ 61,  90,  85,  67,  76],
       [ 86,  68,  59,  63,  58],
       [ 59,  56, 100,  70,  57],
       [ 70,  74,  63,  84,  54],
       [ 56,  65,  57, 100,  85],
       [ 61, 100,  70,  90,  54],
       [ 93,  58,  73,  76,  76],
       [ 94,  93,  54,  81,  79],
       [ 82,  55,  87,  71,  52],
       [ 70,  88,  99,  64,  99],
       [ 72,  64,  63,  65,  92],
       [ 90,  50,  82,  88,  69],
       [ 75,  

In [7]:
#第一位學生的分數
scores[0] #(5,)
scores[0,:] #(5,)
scores[0:1,:] #(1, 5)

array([[58, 79, 78, 92, 81]], dtype=int32)

In [8]:
#前5位學生
scores[:5]
#前5位學生,前3個分數
scores[:5,:3]

array([[ 58,  79,  78],
       [ 76, 100,  87],
       [ 53,  71,  73],
       [ 68,  72,  63],
       [ 84,  77,  93]], dtype=int32)

In [9]:
#第1科分數
scores[:,0]
scores[:,1]
scores[:,2]

array([ 78,  87,  73,  63,  93,  78,  72,  69,  76,  78,  98,  61,  80,
        62,  51,  78,  98,  85,  59, 100,  63,  57,  70,  73,  54,  87,
        99,  63,  82,  64,  68,  62,  92,  57,  74,  58,  83,  95,  55,
        51, 100,  58,  57,  73,  86,  98,  75,  65,  56,  66], dtype=int32)

In [10]:
#ndarray可以陣列運算
total = scores[:,0] + scores[:,1] + scores[:,2] + scores[:,3] + scores[:,4]
total

array([388, 409, 355, 363, 438, 381, 391, 335, 352, 392, 356, 365, 377,
       355, 390, 412, 378, 379, 334, 342, 345, 363, 375, 376, 401, 347,
       420, 356, 379, 383, 309, 325, 413, 361, 384, 311, 323, 412, 331,
       362, 448, 332, 370, 395, 418, 319, 343, 333, 368, 362], dtype=int32)

In [11]:
total / 5

array([77.6, 81.8, 71. , 72.6, 87.6, 76.2, 78.2, 67. , 70.4, 78.4, 71.2,
       73. , 75.4, 71. , 78. , 82.4, 75.6, 75.8, 66.8, 68.4, 69. , 72.6,
       75. , 75.2, 80.2, 69.4, 84. , 71.2, 75.8, 76.6, 61.8, 65. , 82.6,
       72.2, 76.8, 62.2, 64.6, 82.4, 66.2, 72.4, 89.6, 66.4, 74. , 79. ,
       83.6, 63.8, 68.6, 66.6, 73.6, 72.4])

In [12]:
#np內的function
np.sum(scores,axis=1)
np.mean(scores,axis=1)

array([77.6, 81.8, 71. , 72.6, 87.6, 76.2, 78.2, 67. , 70.4, 78.4, 71.2,
       73. , 75.4, 71. , 78. , 82.4, 75.6, 75.8, 66.8, 68.4, 69. , 72.6,
       75. , 75.2, 80.2, 69.4, 84. , 71.2, 75.8, 76.6, 61.8, 65. , 82.6,
       72.2, 76.8, 62.2, 64.6, 82.4, 66.2, 72.4, 89.6, 66.4, 74. , 79. ,
       83.6, 63.8, 68.6, 66.6, 73.6, 72.4])

In [13]:
#實體方法
scores.sum(axis=1)
scores.mean(axis=1)

array([77.6, 81.8, 71. , 72.6, 87.6, 76.2, 78.2, 67. , 70.4, 78.4, 71.2,
       73. , 75.4, 71. , 78. , 82.4, 75.6, 75.8, 66.8, 68.4, 69. , 72.6,
       75. , 75.2, 80.2, 69.4, 84. , 71.2, 75.8, 76.6, 61.8, 65. , 82.6,
       72.2, 76.8, 62.2, 64.6, 82.4, 66.2, 72.4, 89.6, 66.4, 74. , 79. ,
       83.6, 63.8, 68.6, 66.6, 73.6, 72.4])